spring.application.name=softcomp
spring.mongodb.uri=mongodb://localhost:27017/softcomp
mqtt:
    broker-url: tcp://localhost:1883
    client-id: softcomp-client
    username: brice.bopda-fokou@stud.hs-bochum.de
    password: 12345678
    topic: softcomp/topic