spring.application.name=softcomp
spring.mongodb.uri=mongodb://localhost:27017/softcomp
mqtt.broker-url: tcp://sr-labor.ddns.net:1883
mqtt.client-id: softcomp-client
mqtt.username: brice.bopda-fokou@stud.hs-bochum.de
mqtt.password: 018375437
mqtt.topics-wago: Wago750/Status,Wago750/Control
mqtt.topics-siemens: S7_1500/Temperatur/Ist,S7_1500/Temperatur/Differenz,S7_1500/Temperatur/Soll
server.port=8090